version: '3.1'

services:

  mpd-back:
    build: ./mpd-back
    restart: always
    ports:
      - 8087:8080
    volumes:
      - ./custom/:/custom
      - ./logs/:/logs

  mpd-search:
    build: ./mpd-search-engine
    restart: always
    volumes:
      - ./custom/:/custom
        - ./logs/:/logs

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    environment:
      - discovery.type=single-node
      -
    volumes:
      - ./data:/usr/share/elasticsearch/data
