version: '3.1'

services:

  mpd-back:
    build: ./mpd-back
    restart: always
    ports:
      - 8087:8080
    volumes:
      - ./custom/:/custom
      - ./logs/:/logs

  mpd-search:
    build: ./mpd-search-engine
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./custom/:/custom
        - ./logs/:/logs
