package ru.net.arh.mpd.model.sockjs;

public enum ResponseType {
    CONNECTION_STATE
    , PLAYLIST
    , SONG_TIME
    , STATUS
    , PLAYLIST_CLEAR
    , PLAYER
    , CHANGE_CONNECTION_STATE
    , TREE
    , FULL_TREE
    , OUTPUT
    , PLAYLIST_ADD
    , PLAYLIST_ADD_FILE
    , STORED_PLAYLISTS
    , STORED_PLAYLIST
    , UPDATE_DB
    , STREAM_URL
    , STORED_PLAYLIST_LOAD
    , STORED_PLAYLIST_ADD
    , STORED_PLAYLIST_RM
    , STORED_PLAYLIST_SAVE
    , STORED_PLAYLIST_RENAME
    , RANDOM
    , REPEAT
    , SINGLE
    , CONSUME
    , PLAYLIST_SHUFFLE
    , PLAYLIST_RM
    , PLAYLIST_MOVE
    , SEARCH
    , SEARCH_NEW
    , PLAYLIST_ADD_SEARCH
    ;

}
