export const ON_SOCKS_DISCONNECTED = 'ON_SOCKS_DISCONNECTED';
export const ON_SOCKS_CONNECTED = 'ON_SOCKS_CONNECTED';
export const SOCKS_CONNECT = 'SOCKS_CONNECT';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const CONNECTION_STATE = 'CONNECTION_STATE';

