server:
  port: 9090

mpdback:
  defaultAddress: ws://localhost:8080/javaclient


management:
  endpoints:
    web:
      exposure:
        include: "*"

elasticsearch:
  host: localhost
  port: 9200
  protocol: http
