mpdserver:
  defaulthost: localhost
  defaultport: 6600
  defaultpassword: 12345678
  defaultpinginterval: 15000
  defaultStreamUrl: http://localhost:8000/mpd.mp3

searchEngine:
  url: http://localhost:9090/search